#!/usr/bin/env node
/**
 * set-version.js — sets the version in every place that has to agree.
 *
 * The CLI and the VS Code extension are released together, and `check-versions.js`
 * fails the build when they drift. Nothing put them in step, though, so a release
 * meant editing two package.json files (and their lockfiles) by hand and finding
 * out at `prepublishOnly` when you missed one. This is the other half of that pair.
 *
 * `vscode-extension/bundled/` is deliberately not touched: it is a build artifact,
 * regenerated by `npm run bundle`, and check-versions.js already fails on a stale one.
 *
 *   node scripts/set-version.js 1.1.0
 *   npm run version:set -- 1.1.0
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

/** package.json / package-lock.json pairs that must carry the same version. */
const TARGETS = [
    { manifest: ['package.json'], lock: ['package-lock.json'] },
    { manifest: ['vscode-extension', 'package.json'], lock: ['vscode-extension', 'package-lock.json'] },
];

function fail(message) {
    console.error(`Error: ${message}`);
    process.exit(1);
}

/**
 * Rewrites the top-level `"version"` of a hand-formatted manifest, as text.
 *
 * NOT a JSON round-trip: `vscode-extension/package.json` keeps things like
 * `"enum": ["", "pdf", …]` and `"items": { "type": "string" }` on one line, and
 * re-serialising explodes every one of them — turning a version bump into a
 * 16-line reformat that buries the actual change. Only depth-1 keys sit at two
 * spaces, and `version` appears once, so the anchored match is unambiguous; it
 * asserts that rather than assuming it.
 */
function setManifestVersion(absPath, version) {
    const original = fs.readFileSync(absPath, 'utf8');

    const re = /^ {2}"version": "[^"]*",?$/gm;
    const matches = original.match(re) ?? [];
    if (matches.length !== 1)
        fail(`expected exactly one top-level "version" in ${path.relative(ROOT, absPath)}, found ${matches.length}`);

    const updated = original.replace(re, (line) => line.replace(/"version": "[^"]*"/, `"version": "${version}"`));
    if (updated === original) return false;
    fs.writeFileSync(absPath, updated, 'utf8');
    return true;
}

/**
 * Rewrites both `version` fields of a package-lock.
 *
 * A round-trip is safe here, unlike the manifest above: npm generates lockfiles
 * with plain two-space `JSON.stringify`, so re-serialising reproduces the file
 * byte for byte apart from the change.
 */
function setLockVersion(absPath, version) {
    if (!fs.existsSync(absPath)) return false;
    const original = fs.readFileSync(absPath, 'utf8');
    const data = JSON.parse(original);

    data.version = version;
    if (data.packages && data.packages['']) data.packages[''].version = version;

    const updated = JSON.stringify(data, null, 2) + (original.endsWith('\n') ? '\n' : '');
    if (updated === original) return false;
    fs.writeFileSync(absPath, updated, 'utf8');
    return true;
}

function main() {
    const version = process.argv[2];
    if (!version) fail('no version given.\n  Usage: node scripts/set-version.js <version>');

    // Same shape npm version accepts, minus the ranges: a plain semver, with an
    // optional prerelease tag.
    if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version))
        fail(`"${version}" is not a semver version (expected e.g. 1.2.3 or 1.2.3-rc.1).`);

    const changed = [];

    for (const target of TARGETS) {
        const manifest = path.join(ROOT, ...target.manifest);
        if (!fs.existsSync(manifest)) fail(`missing ${path.relative(ROOT, manifest)}`);

        if (setManifestVersion(manifest, version))
            changed.push(path.relative(ROOT, manifest));

        // Lockfiles carry the version twice: at the root and in the "" package entry.
        const lock = path.join(ROOT, ...target.lock);
        if (setLockVersion(lock, version))
            changed.push(path.relative(ROOT, lock));
    }

    if (changed.length === 0) {
        console.log(`Already at ${version} — nothing to change.`);
        return;
    }

    console.log(`Set version ${version} in:`);
    for (const f of changed) console.log(`  ${f}`);
    console.log('\nNext: update CHANGELOG.md, commit, then tag with  git tag v' + version);
}

main();
